theme: "hugo-PaperMod"
baseURL: https://joeypetosa.com/
languageCode: en-us
title: joey petosa

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-XNLPGFEEDW

menu:
  main:
    - name: about
      url: "/about/"
      weight: 1
    - name: portfolio
      url: "/portfolio/"
      weight: 2
    - name: archive
      url: "/archive/"
      weight: 3
    - name: categories
      url: "/categories/"
      weight: 4
    - name: search
      url: "/search/"
      weight: 5

params:
  env: production
  keywords: [Portfolio, DataAnalyis, R, EventManagement, Programming]
  defaultTheme: auto
  disableThemeToggle: false
  
  ShowToc: false
  TocOpen: false
  ShowBreadCrumbs: false
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  displayFullLangName: true
  
  homeInfoParams:
    Content: "event manager, data analyst, footballer"
    title: "joey petosa"
  
  profileMode:
    enabled: true
    title: "joey petosa"
    subtitle: "event manager, data analyst, footballer"
    imageUrl: "https://assets.joeypetosa.com/jp_profile.png"
    imageTitle: "me" # optional

  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/joey-petosa/"
    - name: "Github"
      url: "https://github.com/joeypetosa/"
    - name: "Goodreads"
      url: "https://www.goodreads.com/user/show/93916801-joey-petosa"
    - name: "Spotify"
      url: "https://open.spotify.com/user/joeypetosa"

      
  assets:
    favicon: "https://assets.joeypetosa.com/favicon.ico"
    favicon16x16:  "https://assets.joeypetosa.com/favicon-16x16.png"
    favicon32x32:  "https://assets.joeypetosa.com/favicon-32x32.png"
    apple_touch_icon:  "apple-touch-icon.png"
    android_chrome_192x192:  "https://assets.joeypetosa.com/android-chrome-192x192.png"
    android_chrome_512x512:  "https://assets.joeypetosa.com/android-chrome-512x512.png"
  
taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON