theme: "hugo-PaperMod"
baseURL: https://joeypetosa.com/
languageCode: "en-us"
title: "joey petosa"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-XNLPGFEEDW

menu:
  main:
    - name: about
      url: "/about/"
      weight: 1
      identifier: "about"
    - name: portfolio
      url: "/portfolio/"
      weight: 2
      identifier: "portfolio"
    - name: skills
      url: "/skills/"
      weight: 3
      identifier: "skills"
    - name: contact
      url: "/contact/"
      weight: 4
      identifier: "contact"
    - name: search
      url: "/search/"
      weight: 5
      identifier: "search"

params:
  env: production
  description: joey's website - https://joeypetosa.com
  keywords: [Portfolio, Data Analytics, R, Event Management, Programming, Event Prouction, Data Analyst]
  defaultTheme: auto
  disableThemeToggle: false
  assets:
    favicon: "https://assets.joeypetosa.com/favicon.ico"
    favicon16x16:  "https://assets.joeypetosa.com/favicon-16x16.png"
    favicon32x32:  "https://assets.joeypetosa.com/favicon-32x32.png"
    apple_touch_icon:  "https://assets.joeypetosa.com/apple-touch-icon.png"
    android_chrome_192x192:  "https://assets.joeypetosa.com/android-chrome-192x192.png"
    android_chrome_512x512:  "https://assets.joeypetosa.com/android-chrome-512x512.png"
  label:
    icon: "https://assets.joeypetosa.com/apple-touch-icon-label.png"
    iconHeight: 35
  ShowToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  displayFullLangName: true
  meta:
    author: "Joey Petosa"
    titleSeparator: " | "
  
  homeInfoParams:
    Content: "event manager, data analyst, footballer"
    title: "joey petosa"
  
  profileMode:
    enabled: true
    title: "joey petosa"
    subtitle: "event manager, data analyst, footballer, lifelong learner"
    imageUrl: "https://assets.joeypetosa.com/jp_profile.png"
    imageTitle: "me" # optional

  socialIcons:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/joey-petosa/"
    - name: "Github"
      url: "https://github.com/joeypetosa/"
    - name: "Goodreads"
      url: "https://www.goodreads.com/user/show/93916801-joey-petosa"
    - name: "Spotify"
      url: "https://open.spotify.com/user/joeypetosa"

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  post: "/sections[1-2]/:slug/"
  series: "/sections[1-2]/:slug/"

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
  disqus:
    disable: "false"
  
  googleAnalytics:
    anonymizeIP: "true"
    disable: "false"
    respectDoNotTrack: "false"
    useSessionStorage: "false" 
  
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
      disableInlineCSS: true
  twitter:
      disableInlineCSS: true
      
cover:
  thumbnailInList: true
  