---
title: "ISB Virtual Microbiome Series"
author: "joey petosa"
date: '2022-01-28'
slug: microbiome-series
categories:
- events
- virtual events
tags:
- event
- virtual event
- ISB
---


## About  
As Event Manager and Technical Director for ISB's Virtual Microbiome Series, I 
led the event's core organizing team, ran production operations, and was 
responsible for overall project management throughout the event's lifecycle.  

* [2021 ISB Virtual Microbiome Series](https://isbscience.org/microbiome2021/)  
* [2020 ISB Virtual Microbiome Series](https://isbscience.org/microbiome2020/)

>Event Evolution During a Pandemic: “A crisis is a terrible thing to waste."  

When ISB, along with the rest of the world, had to cancel all of our in-person 
events in 2020 due to the COVID-19 pandemic, I saw an opportunity to try 
something novel. It was clear that we needed to adapt our events for the present, 
but we also needed to strengthen them for the future. I proposed an idea to one 
of our faculty members: "Let's host a virtual microbiome series." He agreed, 
and we haven't looked back since.  

Along with my faculty counterpart, I led an internal team of fifteen scientists 
and administrative staff in organizing every facet of this series. I ran 
bi-weekly project meetings, developed production schedules, advanced speakers, 
scheduled code run-throughs, led dress-rehearsals, communicated with attendees 
and was respsonible for onsite livestream production. 

The series includes two events - an intensive computational course led by ISB 
scientists and a symposium featuring prominent microbiome researchers from across 
the world. Both events were virtual and free in order to make them as globally 
accessible as possible. An internet connection was the only requirement to 
participate. The intended audience was graduate students, postdocs, principal 
investigators, industry scientists, educators, clinicians, or any other variety 
of microbiome-curious person from across the globe.

## By the numbers    
We had remarkable growth in attendance for this series in the past two years. 
We went from 713 registered attendees in 2020 to 2,274 in 2021, which is a 
219% increase. There were 81 countries represented from around the world, as 
well as 45 US states. I’ve provided some data visualizations below that outline 
how successful this series was in 2021.


<div style="align: center; margin-left: -150px;"> 
  <iframe src="https://public.tableau.com/views/2021ISBVirtualMicrobiomeSeriesRegistrationMap/2021ISBVirtualMicrobiomeSeries?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link" width="800px" height="827px" frameborder="0">
  </iframe>
</div>


